export const MYSQL_PROVIDER = 'MYSQL_PROVIDER';

export const DEVICE_REPOSITORY = 'DEVICE_REPOSITORY';
export const EMAIL_REPOSITORY = 'EMAIL_REPOSITORY';
export const SIMCARD_REPOSITORY = 'SIMCARD_REPOSITORY';
export const EWALLET_TYPE_REPOSITORY = 'EWALLET_TYPE_REPOSITORY';
export const EWALLET_REPOSITORY = 'EWALLET_REPOSITORY';
export const EWALLET_TOPUP_REPOSITORY = 'EWALLET_TOPUP_REPOSITORY';
export const PRODUCT_REPOSITORY = 'PRODUCT_REPOSITORY';
export const PRODUCT_VARIANT_REPOSITORY = 'PRODUCT_VARIANT_REPOSITORY';
export const PLATFORM_REPOSITORY = 'PLATFORM_REPOSITORY';
export const PLATFORM_PRODUCT_REPOSITORY = 'PLATFORM_PRODUCT_REPOSITORY';
export const PRODUCT_ACCOUNT_REPOSITORY = 'PRODUCT_ACCOUNT_REPOSITORY';
export const PRODUCT_ACCOUNT_USER_REPOSITORY =
  'PRODUCT_ACCOUNT_USER_REPOSITORY';
export const TRANSACTION_REPOSITORY = 'TRANSACTION_REPOSITORY';
